eCars.WebUI/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eCars.Domain.Interfaces;
using eCars.Domain.Repository;
using Microsoft.AspNet.Identity;
using eCars.WebUI.Models;

namespace eCars.WebUI.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        #region Instance Variables
        private readonly ICustomerRepository _repoCustomer;
        private readonly IVehiclePlanRepository _repoPlan;
        #endregion

        public CustomerController()
        {
            _repoCustomer = new CustomerRepository();
            _repoPlan = new VehiclePlanRepository();
        }

        [AllowAnonymous]
        public ActionResult Dealers()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult GetDealers()
        {
            var dealers = _repoCustomer.GetDealers();
            var data = new CustomerViewModel().Map(dealers);
            return PartialView(data);
        }

        [AllowAnonymous]
        public ActionResult Plans()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult GetPlan()
        {
            var plans = _repoPlan.GetPlans();
            return PartialView("PlansPartial", plans);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult ChoosePlan(string planId)
        {
            if (int.Parse(planId) > 1)
            {
                return RedirectToAction("ChoosePaymentPlan");
            }
            var userId = User.Identity.GetUserId();
            if (string.IsNullOrEmpty(userId)) return View("UserNotFound");
            
            var done = _repoPlan.Update(int.Parse(planId), userId);
            if (int.Parse(planId) > 1) RedirectToAction("");

            if (done == -1)
            {
                return View("BasicPlanActivated");
            }
            else
            {
                return Json("El plan no pudo ser seleccionado, por favor llamenos.", JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult ChoosePaymentPlan()
        {
            return View();
        }


    }
}

eCars.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using eCars.Domain.Entities;
using eCars.Domain.Interfaces;
using eCars.Domain.Repository;
using eCars.WebUI.Models;
using eCars.WebUI.Service;

namespace eCars.WebUI.Controllers
{
    public class HomeController : Controller
    {
        #region Instance Variable

        private IVehicleRepository _repoVehicle;
        private MailService _mailService;
        private readonly IVehiclePhotoRepository _repoVehiclePhoto;

        public HomeController()
        {
            _repoVehicle = new VehicleRepository();
            _repoVehiclePhoto = new VehiclePhotoRepository();
            _mailService = new MailService();
        }
        #endregion
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Title = "EnAutos.com :: Inicio";
            return View();
        }

        public ActionResult AboutUs()
        {
            ViewBag.Title = "EnAutos.com :: Sobre Nosotros";
            return View();
        }

        public FileResult Robotstxt()
        {
            var path = Server.MapPath("~/Views/Shared/Robots.txt");
            var file = File(path, "application/text");
            return file;
        }

        public ActionResult Highlights()
        {
            var vehicleList = _repoVehicle.GetVehicleHighlights();
            var model = new VehicleViewModel();
            var photos = _repoVehiclePhoto.SearchFor(vehicleList);
            var result = model.BindVehicleAndPhotos(vehicleList, photos);
            return PartialView(result);
        }
        [HttpPost]
        public ActionResult SendEmail(string name, string email, string phone, string subject, string message)
        {
            var req = Request["subjecttxt"];
            Task.Factory.StartNew(() =>
            {
                _mailService.SendContactEmail(name, email, phone, subject, message);
            });
            return Json("Enviado", JsonRequestBehavior.AllowGet);
        }

        public ActionResult PrivacyPolicy()
        {
            return View();
        }
    }
}

eCars.WebUI/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;
using eCars.Domain.Entities;
using eCars.Domain.Interfaces;
using eCars.Domain.Repository;
using eCars.WebUI.Models;
using PagedList;
using Postal;
using System.Configuration;

namespace eCars.WebUI.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        #region Instance Variables
        private IVehicleRepository _repoVehicle;
        private readonly IMakeAndModelRepository _repoMakeAndModel;
        private readonly IMotorRepository _repoMotor;
        private readonly ITransmissionRepository _repoTransmission;
        private readonly IFuelRepository _repoFuel;
        private readonly IDriveTrainRepository _repoDriveTrain;
        private readonly IConditionRepository _repoCondition;
        private readonly IPublicationRepository _repoPublication;
        private readonly ICurrencyRepository _repoCurrency;
        private readonly IVehiclePhotoRepository _repoVehiclePhoto;
        private readonly IStateRepository _repoState;
        private readonly ICustomerRepository _repoCustomer;
        private readonly IVehiclePlanRepository _repoPlan;
        private readonly IColorRepository _repoColor;
        #endregion

        #region Constructor

        public VehicleController()
        {
            _repoVehicle = new VehicleRepository();
            _repoMakeAndModel = new MakeAndModelRepository();
            _repoMotor = new MotorRepository();
            _repoTransmission = new TransmissionRepository();
            _repoFuel = new FuelRepository();
            _repoDriveTrain = new DriveTrainRepository();
            _repoCondition = new ConditionRepository();
            _repoCurrency = new CurrencyRepository();
            _repoPublication = new PublicationVehicleRepository();
            _repoVehiclePhoto = new VehiclePhotoRepository();
            _repoState = new StateRepository();
            _repoCustomer = new CustomerRepository();
            _repoPlan = new VehiclePlanRepository();
            _repoColor = new ColorRepository();

        }

        #endregion

        #region Actions


        [AllowAnonymous]
        public ActionResult Search()
        {
            var vehicles = _repoVehicle.GetAll();
            var vehiclePhotos = _repoVehiclePhoto.GetAll();
            var model = new VehicleViewModel();
            var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
            Session["Data"] = null;
            var result = GeneratePagination(list, 1);
            return View(result);
        }


        [AllowAnonymous]
        public ActionResult Detail(int id)
        {
            if (id == 0) return RedirectToAction("Search");

            var vehicle = _repoVehicle.GetById(id);
            var customer = _repoCustomer.GetCustomerByVehicleId(vehicle.VehicleId);
            var customerModel = new CustomerViewModel();
            var list = new List<Vehicle>();
            var model = new VehicleViewModel();
            list.Add(vehicle);
            var photos = _repoVehiclePhoto.SearchFor(list);
            var vehicleModel = model.BindVehicleAndPhotos(list, photos);
            var result = vehicleModel.FirstOrDefault();
            var data = new List<Customer>();
            data.Add(customer);
            result.CustomerViewModel = customerModel.Map(data).FirstOrDefault();
            return View(result);
        }


        [AllowAnonymous]
        public ActionResult Similiar(int id)
        {
            var vehicleList = _repoVehicle.GetSimilarVehicles(id);
            if (!vehicleList.Any()) return PartialView(new List<VehicleViewModel>());
            var model = new VehicleViewModel();
            var photos = _repoVehiclePhoto.SearchFor(vehicleList);
            var result = model.BindVehicleAndPhotos(vehicleList, photos);
            return PartialView(result);
        }

        #endregion

        #region Vehicle CRUD

        [HttpGet]
        public ActionResult Create()
        {
            var model = InitializeVehicleModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(VehicleViewModel vehicleViewModel)
        {
            var isValidCreate = CreateValidation();
            if (isValidCreate) return View(InitializeVehicleModel());
            try
            {
                // TODO: Add insert logic here
                var vehicle = vehicleViewModel.MapVehicle(vehicleViewModel);
                var vehicleId = _repoVehicle.Insert(vehicle);
                var userId = User.Identity.GetUserId();
                var user = _repoCustomer.GetById(userId);

                //Automatic assign publication
                _repoPublication.Insert(new Publication { Active = false, CustomerId = user.User_Id_performance, VehicleId = vehicleId, PublicationId = 0, Expired = false });
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Ajax Calls

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetModels(string makes)
        {
            var result = _repoMakeAndModel.GetModelByMake(makes).ToSelectListItems(makes);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetMakesAndModels()
        {
            var result = _repoMakeAndModel.GetMakesAndModels();
            var data = from a in result select a.Make + " " + a.Model;
            return Json(data.ToArray(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetClientVehiclesByCustomer()
        {
            var userId = User.Identity.GetUserId();
            var result = _repoVehicle.GetVehiclesByCustomerId(userId);
            var data = from a in result select new { Text = a.Make + " " + a.Model + " " + a.Year, Value = a.VehicleId };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Filters

        [AllowAnonymous]
        public ActionResult SearchFor(string makeAndModel)
        {
            var list = SearchVehicleByMakeAndModel(makeAndModel);
            Session["Data"] = list;
            var result = GeneratePagination(list, 1);
            return PartialView("ProductGrid", result);
        }

        [AllowAnonymous]
        public ActionResult FilterByYear(short yearFrom, short yearTo, string makeAndModel = "")
        {
            if (Session["Data"] == null)
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => (a.Year >= yearFrom && a.Year <= yearTo));
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var list = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = list.Where(a => (a.Year >= yearFrom && a.Year <= yearTo));
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);

                return PartialView("ProductGrid", result);
            }
        }

        [AllowAnonymous]
        public ActionResult FilterByState(short stateId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.StateId == stateId);
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => a.StateId == stateId);
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);

            }
        }
        
        [AllowAnonymous]
        public ActionResult FilterByFuelId(short fuelId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.FuelId == fuelId);
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => a.FuelId == fuelId);
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);

            }
        }

        [AllowAnonymous]
        public ActionResult FilterByConditionId(short conditionId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.VehicleConditionId == conditionId);

eCars.WebUI/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "enAutos.com :: Nosotros";
}


<!-- Page Title
 ================================================== -->
<section class="page-title dark-bg page-bg">
    <!-- Overlay -->
    <div class="overlay">
        <!-- Container -->
        <div class="container">

            <!-- Title -->
            <div class="section-title">
                <h2>Sobre Nosotros</h2>
                <div class="line"></div>
                <p>Somos un equipo que innova.</p>
            </div>
            <!-- Title /END -->
        </div>
        <!-- /Container -->
    </div>
    <!-- /Overlay -->
</section>
<!-- /Page Title
================================================== -->

<!-- Content Block
================================================== -->
<section class="content-block default-bg">

    <!-- Container -->
    <div class="container">
        <!-- Row -->
        <div class="row">

            <!-- Column -->
            <div class="col-sm-6 col-md-6">

                <img src="~/Content/images/backgrounds/2014-model-s-AboutUS.jpg" class="width-95pc fullw-xs" alt="carro">

            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-sm-6 col-md-6 vspace-xs">

                <h4>El mejor servicio</h4>
                <p><span class="dropcap">M</span>&aacute;s que autos, somos tu aliado, te hacemos la vida m&aacute;s f&aacute;cil a la hora de buscar ese auto que tanto quieres y vendemos tu auto m&aacute;s r&aacute;pido de lo podr&iacute;as imaginar. En enAutos.com nos encargamos de buscar y vender tu auto.</p>

                <!-- Nested Row -->
                <div class="row">

                    <!-- Column -->
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <ul class="icon-list">
                            <li><i class="fa fa-check"></i>Te notificamos del auto que buscas</li>
                            <li><i class="fa fa-check"></i>Integrado con las redes sociales</li>
                            <li><i class="fa fa-check"></i>R&aacute;pido</li>
                            <li><i class="fa fa-check"></i>Planes Gratis</li>
                            <li><i class="fa fa-check"></i>F&aacute;cil</li>
                        </ul>
                    </div>
                    <!-- /Column -->
                    <!-- Column -->
                  
                    <!-- /Column -->

                </div>
                <!-- /Nested Row -->

            </div>
            <!-- /Column -->
        </div>
        <!-- Row /END -->

    </div>
    <!-- /Container -->

</section>
<!-- /Content Block
================================================== -->

eCars.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<!-- Content Block
       ================================================== -->
<section class="intro-block page-bg">

    <!-- Overlay -->
    <div class="overlay">

        <!-- Container -->
        <div class="container">

            <!-- Text Slider -->
            <div class="text-slider no-js">
                <!-- Bxslider -->
                <ul class="bxslider" id="text-slider" data-call="bxslider" data-options="parentSelector:'.text-slider', removeParentClass:'no-js', prevText:'', nextText:'', pager:true, controls:false, mode:'horizontal', auto:true, autoReload:true">
                    <li>
                        <div class="slide">
                            <h2>tu veh&iacute;culo puede estar aqu&iacute;.</h2>
                        </div>
                    </li>
                    <li>
                        <div class="slide">
                            <h2>busca tu carro, es super fac&iacute;l.</h2>
                        </div>
                    </li>
                    <li>
                        <div class="slide">
                            <h2>vende tu autom&oacute;vil en minutos</h2>
                        </div>
                    </li>
                    <li>
                        <div class="slide">
                            <h2>la mejor p&aacute;gina de venta y b&uacute;squeda de autos.</h2>
                        </div>
                    </li>
                </ul>
                <!-- /Bxslider -->

                <p class="meta">EnAutos.com vende y busca tu autom&oacute;vil en minutos!.</p>

                <!-- Buttons -->
                <div>
                    <a href="@Url.Action("Login","Account")" class="scroll-to btn btn-primary"><i class="fa fa-sign-in"></i>Acceder</a>
                    <a href="@Url.Action("Search","Vehicle")" class="scroll-to btn btn-white"><i class="fa fa-search"> </i>Busca tu auto</a>
                </div>
                <!-- Buttons -->

            </div>
            <!-- /Text Slider -->
        </div>
        <!-- /Container -->

    </div>
    <!-- /Overlay -->

</section>
<!-- /Content Block
================================================== -->
<!-- Content Block
================================================== -->
<section class="content-block default-bg">

    <!-- Container -->
    <div class="container">

        <!-- Row -->
        <div class="row">

            <!-- Column -->
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="service-box no-border tts-1">
                    <i class="icon fa fa-cloud-upload color-1-bg tts-1-target"></i>
                    <h4 class="u-case">Sube tus automoviles gratis</h4>
                    <p>Puedes subir tu auto inmediatamente, hasta 16 fotos por cada auto, vende y busca tus autos aqu&iacute;.</p>

                </div>

            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="service-box no-border tts-1">
                    <i class="icon fa fa-smile-o color-1-bg tts-1-target"></i>
                    <h4 class="u-case">Lo que ofrecemos</h4>
                    <p>Notificaciones del auto que buscas, compartelo en redes sociales, asegurate de ser el #1 en las b&uacute;squedas.</p>

                </div>
            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="service-box no-border tts-1">
                    <i class="icon fa fa-shopping-cart color-1-bg tts-1-target"></i>
                    <h4 class="u-case">Vende y busca tu autom&oacute;vil</h4>
                    <p>Busca todos los autos que quieras, el mejor precio, los mejores autos.</p>

                </div>
            </div>
            <!-- /Column -->
        </div>
        <!-- /Row-->

    </div>
    <!-- /Container -->

</section>
<!-- /Content Block
================================================== -->
<!-- Content Block
================================================== -->
<section class="content-block page-bg dark-bg">

    <!-- Overlay -->
    <div class="overlay default">

        <!-- Container -->
        <div class="container">
            @{
                Html.RenderAction("Highlights");
            }

        </div>
        <!-- /Container -->

    </div>
    <!-- /Overlay -->

</section>
<!-- /Content Block
================================================== -->
<!-- Content Block
================================================== -->
<section class="content-block default-bg">

    <!-- Container -->
    <div class="container">


        <!-- Title -->
        <div class="section-title">
            <h2>Planes de pago</h2>
            <div class="line color-1-bg"></div>
            <p>Para los que quieren agregar mas a nuestro excelente servicio. precios en RD$, impuestos incluidos.</p>
        </div>
        <!-- Title /END -->
        <!-- Row -->
        <div class="row">

            <!-- Column -->
            <div class="col-sm-3 col-md-3 tts-1">

                <!-- Plan -->
                <div class="price-plan featured">

                    <div class="header">
                        <h4 class="title">B&aacute;sico</h4>
                    </div>

                    <div class="price-box">
                        <h2 class="price tts-1-target">Gratis</h2>
                    </div>

                    <ul class="features">
                        <li><span class="badge">4</span> images por auto</li>
                        <li><span class="badge">30</span> minutos top de b&uacute;queda <span class="badge">1</span> auto</li>
                        <li>Notificamos usuarios (Email)</li>
                        <li><span class="badge">3</span> dias de anuncio</li>
                        <li><span class="badge">1</span> auto m&aacute;ximo</li>
                    </ul>

                    <div class="footer">
                        <a href="@Url.Action("Plans","Customer")" class="btn btn-color">Seleccionar</a>
                    </div>

                </div>
                <!-- /Plan -->
            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-sm-3 col-md-3 tts-1">

                <!-- Plan -->
                <div class="price-plan">

                    <div class="header">
                        <h4 class="title">Standard</h4>
                    </div>

                    <div class="price-box">
                        <h2 class="price tts-1-target">500</h2>
                    </div>

                    <ul class="features">
                        <li><span class="badge">8</span> Imagenes por auto</li>
                        <li><span class="badge">1</span> hora top de b&uacute;queda <span class="badge">1 </span> auto</li>
                        <li>Notificamos usuarios (Email)</li>
                        <li><span class="badge">14</span> dias de anuncio</li>
                        <li><span class="badge">1</span> auto m&aacute;ximo</li>

                    </ul>

                    <div class="footer">
                        <a href="@Url.Action("Plans","Customer")" class="btn btn-color">Seleccionar</a>
                    </div>

                </div>
                <!-- /Plan -->
            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-xs-12 col-sm-3 col-md-3 tts-1">

                <!-- Plan -->
                <div class="price-plan">

                    <div class="header">
                        <h4 class="title">Profesional</h4>
                    </div>

                    <div class="price-box">
                        <h2 class="price tts-1-target">1,000</h2>
                    </div>

                    <ul class="features">
                        <li><span class="badge">12</span> Imagenes por auto</li>
                        <li><span class="badge">2</span> horas top de b&uacute;squeda <span class="badge">2</span> autos</li>
                        <li>Notificamos usuarios <span class="meta">(Email)</span></li>
                        <li><span class="badge">30</span> dias de anuncio</li>
                        <li><span class="badge">2</span> autos m&aacute;ximo</li>
                    </ul>

                    <div class="footer">
                        <a href="@Url.Action("Plans","Customer")" class="btn btn-color">Seleccionar</a>
                    </div>

                </div>
                <!-- /Plan -->
            </div>
            <!-- /Column -->
            <!-- Column -->
            <div class="col-xs-12 col-sm-3 col-md-3 tts-1">

                <!-- Plan -->
                <div class="price-plan">

                    <div class="header">
                        <h4 class="title">Enterprise</h4>
                    </div>

                    <div class="price-box">
                        <h2 class="price tts-1-target">1,500</h2>
                    </div>

                    <ul class="features">
                        <li><span class="badge">16</span> Imagenes por auto</li>
                        <li><span class="badge">5</span> horas top de b&uacute;squeda <span class="badge">5</span> autos</li>
                        <li>Notificamos usuarios (Email)</li>
                        <li><span class="badge">30</span> dias de anuncio</li>
                        <li><span class="badge">5</span> autos m&aacute;ximo</li>
                    </ul>

                    <div class="footer">
                        <a href="@Url.Action("Plans","Customer")" class="btn btn-color">Seleccionar</a>
                    </div>

                </div>
                <!-- /Plan -->
            </div>
            <!-- /Column -->

        </div>
        <!-- /Row -->

    </div>
    <!-- /Container -->
</section>
<!-- /Content Block
================================================== -->
<!-- Content Block
================================================== -->
<section class="content-block default-bg">
    <!-- Container -->
    <div class="container">

        <!-- Title -->
        <div class="section-title">
            <h2>Quieres m&aacute;s informaci&oacute;n</h2>
            <div class="line"></div>
            <p>Escribenos.</p>
        </div>
        <!-- Title /END -->
        <!-- Contact Form -->
        <div class="contact-form home-contact">
            
            <!-- Wrapper -->
            <div class="clearfix">

                <!-- Left Col -->
                <form id="emailForm" action="" role="form">
                    <div class="pull-left col">

                        <input type="text" class="form-control" id="nametxt" placeholder="Nombre completo">
                        <input type="text" class="form-control" id="emailtxt"placeholder="E-Mail">

                        <!-- Map -->
                        <div class="map">
                            <div class="overlay">
                                <div class="link">
                                    <a href="#" data-toggle="modal" data-target="#map-modal"><i class="fa fa-expand"></i>Ver mapa</a>
                                </div>
                            </div>
                        </div>
                        <!-- /Map -->
                    </div>
                    <!-- /Left Col -->
                    <!-- Right Col -->
                    <div class="pull-right col">

                        <input type="text" class="form-control" id="phonetxt" placeholder="Tel&eacute;fono.">
                        <input type="text" class="form-control" id="subjecttxt" placeholder="Asunto">
                        <textarea class="form-control" id="messagetxt" placeholder="Tu Mensaje"></textarea>
                        <button type="submit" class="btn btn-primary" id="homeEmailbtn">Mandar Email</button>

                    </div>
                </form>
                
                <!-- /Right Col -->


            </div>
            <!-- /Wrapper -->
            <!-- Map Modal -->
            <div id="map-modal" class="map-modal modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Our Map Location</h4>
                        </div>
                        <div class="modal-body">
                            <iframe id="gmap" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Facebook+Inc.,+Earlham+Street,+London,+United+Kingdom&amp;aq=4&amp;oq=facebook&amp;sll=37.0625,-95.677068&amp;sspn=38.963048,56.513672&amp;ie=UTF8&amp;hq=Facebook+Inc.,+Earlham+Street,&amp;hnear=London,+United+Kingdom&amp;t=m&amp;cid=7509567643069030052&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
                            <script type="text/javascript">
                                // Delay loading iframe for better performance
                                var iframe = document.getElementById('gmap');
                                var src = iframe.src;
                                iframe.src = '';
                                window.onload = function () { iframe.src = src; }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Map Modal -->

        </div>
        <!-- /Contact Form -->

    </div>
    <!-- /Container -->
</section>
<!-- /Content Block
================================================== -->
<script src="@Url.Content("~/Scripts/vehicleHome.js")"></script>