eCars.WebUI/Controllers/PublishController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eCars.Domain.Interfaces;
using eCars.Domain.Repository;
using eCars.WebUI.Models;
namespace eCars.WebUI.Controllers
{
    public class PublishController : Controller
    {
        private readonly IPublicationRepository _repoPublication;
        private PublicationViewModel _publicationView;

        public PublishController()
        {
            _publicationView = new PublicationViewModel();
            _repoPublication = new PublicationVehicleRepository();
        }

        // GET: Publish
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetPublications()
        {
            var userId = User.Identity.GetUserId();
            var data = _repoPublication.SearchFor(userId);

            var model = _publicationView.Map(data);
            return PartialView(model);
        }

        [HttpGet]
        public JsonResult PublishVehicle(int publishId)
        {
            var userId = User.Identity.GetUserId();
            var result = _repoPublication.Publish(publishId, userId);
            if (result != 0)
            {
                return Json("Publicado", JsonRequestBehavior.AllowGet);    
            }
            return Json("No se pudo publicar", JsonRequestBehavior.AllowGet);
        }

    }
}

eCars.WebUI/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;
using eCars.Domain.Entities;
using eCars.Domain.Interfaces;
using eCars.Domain.Repository;
using eCars.WebUI.Models;
using PagedList;
using Postal;
using System.Configuration;

namespace eCars.WebUI.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        #region Instance Variables
        private IVehicleRepository _repoVehicle;
        private readonly IMakeAndModelRepository _repoMakeAndModel;
        private readonly IMotorRepository _repoMotor;
        private readonly ITransmissionRepository _repoTransmission;
        private readonly IFuelRepository _repoFuel;
        private readonly IDriveTrainRepository _repoDriveTrain;
        private readonly IConditionRepository _repoCondition;
        private readonly IPublicationRepository _repoPublication;
        private readonly ICurrencyRepository _repoCurrency;
        private readonly IVehiclePhotoRepository _repoVehiclePhoto;
        private readonly IStateRepository _repoState;
        private readonly ICustomerRepository _repoCustomer;
        private readonly IVehiclePlanRepository _repoPlan;
        private readonly IColorRepository _repoColor;
        #endregion

        #region Constructor

        public VehicleController()
        {
            _repoVehicle = new VehicleRepository();
            _repoMakeAndModel = new MakeAndModelRepository();
            _repoMotor = new MotorRepository();
            _repoTransmission = new TransmissionRepository();
            _repoFuel = new FuelRepository();
            _repoDriveTrain = new DriveTrainRepository();
            _repoCondition = new ConditionRepository();
            _repoCurrency = new CurrencyRepository();
            _repoPublication = new PublicationVehicleRepository();
            _repoVehiclePhoto = new VehiclePhotoRepository();
            _repoState = new StateRepository();
            _repoCustomer = new CustomerRepository();
            _repoPlan = new VehiclePlanRepository();
            _repoColor = new ColorRepository();

        }

        #endregion

        #region Actions


        [AllowAnonymous]
        public ActionResult Search()
        {
            var vehicles = _repoVehicle.GetAll();
            var vehiclePhotos = _repoVehiclePhoto.GetAll();
            var model = new VehicleViewModel();
            var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
            Session["Data"] = null;
            var result = GeneratePagination(list, 1);
            return View(result);
        }


        [AllowAnonymous]
        public ActionResult Detail(int id)
        {
            if (id == 0) return RedirectToAction("Search");

            var vehicle = _repoVehicle.GetById(id);
            var customer = _repoCustomer.GetCustomerByVehicleId(vehicle.VehicleId);
            var customerModel = new CustomerViewModel();
            var list = new List<Vehicle>();
            var model = new VehicleViewModel();
            list.Add(vehicle);
            var photos = _repoVehiclePhoto.SearchFor(list);
            var vehicleModel = model.BindVehicleAndPhotos(list, photos);
            var result = vehicleModel.FirstOrDefault();
            var data = new List<Customer>();
            data.Add(customer);
            result.CustomerViewModel = customerModel.Map(data).FirstOrDefault();
            return View(result);
        }


        [AllowAnonymous]
        public ActionResult Similiar(int id)
        {
            var vehicleList = _repoVehicle.GetSimilarVehicles(id);
            if (!vehicleList.Any()) return PartialView(new List<VehicleViewModel>());
            var model = new VehicleViewModel();
            var photos = _repoVehiclePhoto.SearchFor(vehicleList);
            var result = model.BindVehicleAndPhotos(vehicleList, photos);
            return PartialView(result);
        }

        #endregion

        #region Vehicle CRUD

        [HttpGet]
        public ActionResult Create()
        {
            var model = InitializeVehicleModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(VehicleViewModel vehicleViewModel)
        {
            var isValidCreate = CreateValidation();
            if (isValidCreate) return View(InitializeVehicleModel());
            try
            {
                // TODO: Add insert logic here
                var vehicle = vehicleViewModel.MapVehicle(vehicleViewModel);
                var vehicleId = _repoVehicle.Insert(vehicle);
                var userId = User.Identity.GetUserId();
                var user = _repoCustomer.GetById(userId);

                //Automatic assign publication
                _repoPublication.Insert(new Publication { Active = false, CustomerId = user.User_Id_performance, VehicleId = vehicleId, PublicationId = 0, Expired = false });
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Ajax Calls

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetModels(string makes)
        {
            var result = _repoMakeAndModel.GetModelByMake(makes).ToSelectListItems(makes);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetMakesAndModels()
        {
            var result = _repoMakeAndModel.GetMakesAndModels();
            var data = from a in result select a.Make + " " + a.Model;
            return Json(data.ToArray(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetClientVehiclesByCustomer()
        {
            var userId = User.Identity.GetUserId();
            var result = _repoVehicle.GetVehiclesByCustomerId(userId);
            var data = from a in result select new { Text = a.Make + " " + a.Model + " " + a.Year, Value = a.VehicleId };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Filters

        [AllowAnonymous]
        public ActionResult SearchFor(string makeAndModel)
        {
            var list = SearchVehicleByMakeAndModel(makeAndModel);
            Session["Data"] = list;
            var result = GeneratePagination(list, 1);
            return PartialView("ProductGrid", result);
        }

        [AllowAnonymous]
        public ActionResult FilterByYear(short yearFrom, short yearTo, string makeAndModel = "")
        {
            if (Session["Data"] == null)
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => (a.Year >= yearFrom && a.Year <= yearTo));
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var list = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = list.Where(a => (a.Year >= yearFrom && a.Year <= yearTo));
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);

                return PartialView("ProductGrid", result);
            }
        }

        [AllowAnonymous]
        public ActionResult FilterByState(short stateId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.StateId == stateId);
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => a.StateId == stateId);
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);

            }
        }
        
        [AllowAnonymous]
        public ActionResult FilterByFuelId(short fuelId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.FuelId == fuelId);
                Session["Data"] = filteredList;
                var result = GeneratePagination(filteredList, 1);
                return PartialView("ProductGrid", result);
            }
            else
            {
                var vehicles = _repoVehicle.GetAll();
                var vehiclePhotos = _repoVehiclePhoto.GetAll();
                var model = new VehicleViewModel();
                var list = model.BindVehicleAndPhotos(vehicles, vehiclePhotos);
                list = list.Where(a => a.FuelId == fuelId);
                Session["Data"] = list;
                var result = GeneratePagination(list, 1);
                return PartialView("ProductGrid", result);

            }
        }

        [AllowAnonymous]
        public ActionResult FilterByConditionId(short conditionId, string makeAndModel = "")
        {
            if (Session["Data"] != null)
            {
                var data = Session["Data"] as IEnumerable<VehicleViewModel>;
                var filteredList = data.Where(a => a.VehicleConditionId == conditionId);

eCars.WebUI/Views/Vehicle/Create.cshtml
@using System.Web.Optimization
@model eCars.WebUI.Models.VehicleViewModel

@{
    ViewBag.Title = "enAutos.com :: Agregar";
}

@Styles.Render("~/Content/jQuery.FileUpload/css/jquery.fileupload.css")
@Styles.Render("~/Content/jQuery.FileUpload/css/jquery.fileupload-ui.css")

<!-- Page Wrapper
================================================== -->
<div id="page-wrapper">

    <!-- Page Title
    ================================================== -->
    <section class="page-title dark-bg page-bg">
        <!-- Overlay -->
        <div class="overlay">
            <!-- Container -->
            <div class="container">

                <!-- Title -->
                <div class="section-title">
                    <h2>Agrega tu auto</h2>
                    <div class="line"></div>
                    <p>Agrega todos los autos que quieras seg&uacute;n tu plan.</p>
                </div>
                <!-- Title /END -->
            </div>
            <!-- /Container -->
        </div>
        <!-- /Overlay -->
    </section>
    <!-- /Page Title
    ================================================== -->
    <!-- Content Block
    ================================================== -->
    <section class="content-block default-bg">

        <!-- Container -->
        <div class="container">
            <!-- Tab Nav -->
            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a data-toggle="tab" href="#formcarcreate">Auto</a></li>
                <li class="" id="carphototab"><a data-toggle="tab" href="#carphotos">Fotos</a></li>
                <li class="" id="formpublishtab"><a data-toggle="tab" href="#formpublish">Publicar</a></li>
            </ul>
            <!-- /Tab Nav -->
            <div class="tab-content" id="myTabContent">
                <div id="formcarcreate" class="tab-pane fade active in">
                    <div class="form-block clearfix">
                        <!-- Form -->
                        @using (Ajax.BeginForm("Create", new AjaxOptions { UpdateTargetId = "" }))
                        {
                            <div class="pull-left col">
                                <h4><i class="fa fa-cloud-upload"></i>Crear autom&oacute;vil</h4>
                                <hr />


                                @Html.AntiForgeryToken()

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                @Html.LabelFor(model => model.Make, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.Make, Model.Makes, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Make, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.Model, "Seleccione", new { @class = "control-label" })
                                @Html.DropDownList("MakeAndModelId", new SelectList(string.Empty, "Value", "Text"), "Seleccione un modelo", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MakeAndModelId)


                                @Html.LabelFor(model => model.Year, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Year, null, new { @class = "form-control", @type = "number", @max = DateTime.Now.Year + 1 })
                                @Html.ValidationMessageFor(model => model.Year, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.CurrencyId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.CurrencyId, Model.Currencies, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CurrencyId, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.Price, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Price, null, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(model => model.Price, null, new { @class = "text-danger" })



                                @Html.LabelFor(model => model.MotorId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.MotorId, Model.Motors, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MotorId, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.Cilinders, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Cilinders, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(model => model.Cilinders)


                                @Html.LabelFor(model => model.TransmissionId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.TransmissionId, Model.Transmission, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TransmissionId, null, new { @class = "text-danger" })


                            </div>

                            <div class="pull-right col">

                                <h4><i class="fa fa-plus"></i>Datos Adicionales</h4>
                                <hr />

                                @Html.LabelFor(model => model.FuelId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.FuelId, Model.Fuels, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FuelId, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.DriveTrainId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.DriveTrainId, Model.DriveTrains, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DriveTrainId, null, new { @class = "text-danger" })


                                @Html.LabelFor(model => model.VehicleConditionId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.VehicleConditionId, Model.Conditions, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.VehicleConditionId, null, new { @class = "text-danger" })

                                @Html.LabelFor(model => model.StateId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.StateId, Model.States, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.StateId, null, new { @class = "text-danger" })




                                @Html.LabelFor(model => model.TotalSeating, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.TotalSeating, null, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(model => model.TotalSeating)

                                
                                @Html.LabelFor(model => model.ColorExteriorId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.ColorExteriorId, Model.Colors, "Seleccione", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ColorExteriorId)
                                

                                @Html.LabelFor(model => model.ColorInteriorId, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.ColorInteriorId, Model.Colors, new { @class = "form-control "})
                                @Html.ValidationMessageFor(model => model.ColorInteriorId)

                                @Html.LabelFor(model => model.Tags, new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Tags, null, new { @class = "form-control", @data_role = "tagsinput", @maxlength = 350, @placeholder = "Ej: xenon, luces led" })
                                <br />
                                @Html.LabelFor(model => model.Description, new { @class = "control-label" })
                                @Html.TextAreaFor(model => model.Description, new { @cols = "3", @rows = "3", @class = "form-control ", @type = "textarea", @maxlength = 450 })
                                <input type="submit" value="Crear" class="btn btn-primary" />
                            </div>

                        }
                        <!-- /Form -->
                    </div>
                </div>

                <div id="carphotos" class="tab-pane fade">
                    <div class="form-block clearfix">
                        <!--Form-->
                        <form>
                            <div class="pull-left col">
                                @{
                                    Html.RenderPartial("UploadPhotoPartial");
                                }
                            </div>

                            <div class="pull-right col">
                                <div class="bs-callout bs-callout-info">
                                    <h4>Informaci&oacute;n!</h4>
                                    <p>Tamaño m&aacute;ximo 5MB (jpg y png).</p>
                                    <p>Imagenes con el mismo nombre ser&aacute;n reemplazadas.</p>
                                    <p>Suba imagenes de alta calidad :)</p>
                                </div>
                            </div>
                        </form>
                        <!--/Form-->
                    </div>
                </div>

                <div id="formpublish" class="tab-pane fade">
                    <div class="form-block clearfix">
                        
                        <form action="Publish/Publish" method="POST">
                            <div class="clearfix">
                                @{
                                    Html.RenderAction("GetPublications", "Publish");
                                }
                            </div>
                        </form>
                    </div>



                </div>
            </div>
            <!-- /Tabs -->
        </div>
        <!-- /Container -->
    </section>
    <!-- /Content Block
    ================================================== -->
</div>
<!-- /Page Wrapper
    ================================================== -->

<script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload.js")"></script>
<script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-ui.js")"></script>
<script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.iframe-transport.js")"></script>
<script src="@Url.Content("~/Scripts/vehicleCreate.js")"></script>

eCars.WebUI/Views/Vehicle/Search.cshtml
@model PagedList.IPagedList<eCars.WebUI.Models.VehicleViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "EnAutos.com :: Buscar";
}
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/typeaheadjs.css")" />
<!-- Page Title
      ================================================== -->
<section class="page-title dark-bg page-bg">
    <!-- Overlay -->
    <div class="overlay">
        <!-- Container -->
        <div class="container">

            <!-- Title -->
            <div class="section-title">
                <h2>Busca tu Auto</h2>
                <div class="line"></div>
                <p>EnAutos.com, todos los autos que buscas.</p>
                <div class="form-group">
                    <div id="prefetch">
                        <input type="text" id="searchMainTxt" class="form-control typeahead" placeholder="Ej: honda civic" maxlength=64 />

                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" id="vehicelSearchBtn"><i class="fa fa-search">Buscar</i></button>
                    </div>

                </div>

            </div>
            <!-- Title /END -->
        </div>
        <!-- /Container -->
    </div>
    <!-- /Overlay -->
</section>
<!-- /Page Title
    ================================================== -->
@*<section class="page-info-block">

        <!-- Container -->
        <div class="container">
            <!-- Page Info -->
            <div class="page-info clearfix">

                <!-- Search -->
                <p>La mejor forma de buscar</p>
                <!-- /Search -->

            </div>
            <!-- /Page-info -->
        </div>
        <!-- /Container -->

    </section>*@



<!-- Content Block
================================================== -->
<section class="content-block default-bg">

    <!-- Container -->
    <div class="container">
        <!-- Row -->
        <div class="row">
            <!-- Main Col -->
            <div id="main-col" class="col-sm-9 col-md-9">

                <!-- Products Filter -->
                <div class="products-filter clearfix">
                    <div class="display">
                        <span class="show-list" onclick="changeView('list')">Ver Lista<i class="fa fa-th-list"></i></span>
                        <span class="show-grid" onclick="changeView('grid')">Ver Tabla<i class="fa fa-th"></i></span>
                    </div>
                    @*<div class="limit">
                            <b>No</b>
                            <select>
                                <option value="9" selected="selected">9</option>
                                <option value="12">12</option>
                                <option value="15">15</option>
                                <option value="18">18</option>
                            </select>
                        </div>*@
                    <div class="sort">
                        <b>Ordenar Por</b>
                        <select id="searchSortBy">
                            <option value="" selected="selected">Seleccione</option>
                            <option value="1">Año</option>
                            <option value="2">Precio</option>
                        </select>
                    </div>

                </div>
                <!-- /Products Filter -->
                <!-- Product Grid -->
                <ul id="carProductGrid" class="product-grid row">

                    @{
                        Html.RenderPartial("ProductGrid", Model);
                    }
                </ul>
                <!-- /Product Grid -->
                <!-- Pagination -->
                <ul class="pagination">
                    @*<li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">&raquo;</a></li>*@
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                </ul>
                <!-- /Pagination -->

            </div>
            <!-- /Main Col -->
            <!---->
            <!-- Side Col -->
            <div id="side-col" class="col-sm-3 col-md-3">
                <!-- Side Widget -->
                <div class="side-widget">

                    <h5 class="widget-title">Filtros<i class="fa fa-list"></i></h5>

                    <ul class="side-links">
                        <li class="has-children">
                            <a class="btn-link">Año</a><span class="toggle-children"></span>
                            <ul>
                                <li>@Html.DropDownList("Year", Model.FirstOrDefault().Years, "Desde", new { @class = "form-control", @id = "yearFrom" })</li>
                                <li>@Html.DropDownList("Year", Model.FirstOrDefault().Years, "Hasta", new { @class = "form-control", @id = "yearTo" })</li>
                            </ul>
                        </li>
                        <li class="has-children">
                            <a href="#">Precio</a><span class="toggle-children"></span>
                            <ul>
                                <li>@Html.TextBox("PriceFrom", null, new { @class = "form-control", @type = "number", @placeholder ="Desde"})</li>
                                <li>@Html.TextBox("PriceTo", null, new { @class = "form-control", @type = "number", @placeholder = "Hasta, enter para filtrar" })</li>
                            </ul>
                        </li>
                        
                        <li class="has-children">
                            <a href="#">Combustible</a><span class="toggle-children"></span>
                            <ul>
                                <li>@Html.DropDownList("FuelId", Model.FirstOrDefault().Fuels, "Seleccione", new { @class = "form-control" })</li>
                            </ul>
                        </li>
                        <li class="has-children">
                            <a href="#">Condici&oacute;n</a><span class="toggle-children"></span>
                            <ul>
                                <li>@Html.DropDownList("VehicleConditionId", Model.FirstOrDefault().Conditions, "Seleccione", new { @class = "form-control" })</li>
                            </ul>
                        </li>
                        <li class="has-children">
                            <a href="#">Lugares</a><span class="toggle-children"></span>
                            <ul>
                                <li>@Html.DropDownList("StateId", Model.FirstOrDefault().States, "Seleccione", new { @class = "form-control" })</li>
                            </ul>
                        </li>

                    </ul>
                </div>
                <!-- /Side Widget -->
                <!-- Side Widget -->
                @*<div class="side-widget">

                        <h5 class="widget-title">Anuncio pagado<i class="fa fa-tags"></i></h5>
                        <ul class="tags clearfix">
                            <li><a href="#">BMW</a></li>
                            <li><a href="#">Mercedez</a></li>
                            <li><a href="#">Honda</a></li>
                            <li><a href="#">Corolla</a></li>

                        </ul>
                    </div>*@
                <!-- /Side Widget -->

            </div>
            <!-- /Side Col -->
        </div>
        <!-- /Row -->

    </div>
    <!-- /Container -->
</section>
<!-- /Content Block
================================================== -->
<script src="@Url.Content("~/Scripts/vehicleSearch.js")"></script>